/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#00355f',
        'primary-container': '#0f4c81',
        'on-primary': '#ffffff',
        'on-primary-container': '#8ebdf9',
        'primary-fixed': '#d2e4ff',
        'primary-fixed-dim': '#a0c9ff',
        'on-primary-fixed': '#001c37',
        'on-primary-fixed-variant': '#07497d',

        secondary: '#505f76',
        'secondary-container': '#d0e1fb',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#54647a',
        'secondary-fixed': '#d3e4fe',
        'secondary-fixed-dim': '#b7c8e1',
        'on-secondary-fixed': '#0b1c30',
        'on-secondary-fixed-variant': '#38485d',

        tertiary: '#532800',
        'tertiary-container': '#743b00',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#f9a767',
        'tertiary-fixed': '#ffdcc4',
        'tertiary-fixed-dim': '#ffb780',
        'on-tertiary-fixed': '#2f1400',
        'on-tertiary-fixed-variant': '#6f3800',

        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',

        background: '#f7f9fb',
        'on-background': '#191c1e',
        surface: '#f7f9fb',
        'on-surface': '#191c1e',
        'on-surface-variant': '#42474f',
        'surface-variant': '#e0e3e5',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',

        outline: '#727780',
        'outline-variant': '#c2c7d1',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'inverse-primary': '#a0c9ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
        card: '16px',
      },
      spacing: {
        xs: '4px',
        base: '8px',
        sm: '12px',
        md: '24px',
        gutter: '24px',
        lg: '48px',
        xl: '64px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
      },
      fontFamily: {
        display: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      boxShadow: {
        ambient: '0px 4px 20px rgba(0, 0, 0, 0.04)',
      },
    },
  },
  plugins: [],
}
